console.log(" Começamos os estudos oficiais em 2025");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");
console.log("Alterando ");

